#!/usr/bin/env python3
"""
Pre-compute waveform peak data and beat alignment data, writing:
  waveform_peaks.js   — window.WAVEFORM_PEAKS
  alignment_data.js   — window.BEAT_DATA

Requires ffmpeg to be installed (used for decoding MP3 to raw PCM).

Run from the project root:
    python3 generate_peaks.py

Re-run whenever audio files or alignment CSVs are added or replaced.
"""
import subprocess, json, os, math, struct, sys, csv

SRCS = [
    ('short1',      'media/mp3/short1.mp3',      'media/alignments/short1_beats.csv'),
    ('short2',      'media/mp3/short2.mp3',       'media/alignments/short2_beats.csv'),
    ('short_fast1', 'media/mp3/short_fast1.mp3',  'media/alignments/short_fast1_beats.csv'),
    ('short_fast2', 'media/mp3/short_fast2.mp3',  'media/alignments/short_fast2_beats.csv'),
    ('short_slow1', 'media/mp3/short_slow1.mp3',  'media/alignments/short_slow1_beats.csv'),
]

BINS_PER_SEC = 200   # peak resolution: 200 per second
SAMPLE_RATE  = 22050  # downsample to 22050 Hz (sufficient for peaks)


def get_peaks(path: str):
    """Decode audio via ffmpeg and return (duration, peaks_list)."""
    cmd = [
        'ffmpeg', '-y', '-i', path,
        '-ac', '1',              # mono
        '-ar', str(SAMPLE_RATE), # resample
        '-f', 'f32le',           # raw 32-bit float PCM
        'pipe:1',
    ]
    result = subprocess.run(cmd, capture_output=True)
    if result.returncode != 0 and not result.stdout:
        raise RuntimeError(f'ffmpeg failed for {path}:\n{result.stderr.decode()}')

    raw = result.stdout
    n = len(raw) // 4
    if n == 0:
        raise RuntimeError(f'No PCM output from ffmpeg for {path}')

    samples = struct.unpack(f'<{n}f', raw)
    duration = n / SAMPLE_RATE
    num_bins = math.ceil(duration * BINS_PER_SEC)

    peaks = []
    for b in range(num_bins):
        s0 = int(b / num_bins * n)
        s1 = min(int((b + 1) / num_bins * n), n)
        if s1 > s0:
            peak = max(abs(samples[i]) for i in range(s0, s1))
        else:
            peak = 0.0
        peaks.append(round(peak, 4))

    return round(duration, 6), peaks


def get_beats(csv_path: str):
    """Parse a beats CSV and return list of {time, label} dicts."""
    beats = []
    with open(csv_path, newline='') as f:
        reader = csv.DictReader(f)
        for row in reader:
            beats.append({
                'time':  round(float(row['TIME']), 6),
                'label': round(float(row['LABEL'])),
            })
    beats.sort(key=lambda b: b['time'])
    return beats


def main():
    peaks_out = {}
    beats_out = {}

    for name, audio_path, csv_path in SRCS:
        print(f'Processing {name} …', flush=True)

        if not os.path.exists(audio_path):
            print(f'  WARNING: {audio_path} not found, skipping', file=sys.stderr)
            continue
        try:
            duration, peaks = get_peaks(audio_path)
            peaks_out[name] = {'duration': duration, 'peaks': peaks}
            print(f'  {len(peaks)} bins, {duration:.2f} s')
        except Exception as e:
            print(f'  ERROR (peaks): {e}', file=sys.stderr)

        if not os.path.exists(csv_path):
            print(f'  WARNING: {csv_path} not found, skipping beats', file=sys.stderr)
            continue
        try:
            beats = get_beats(csv_path)
            beats_out[name] = beats
            print(f'  {len(beats)} beats')
        except Exception as e:
            print(f'  ERROR (beats): {e}', file=sys.stderr)

    if not peaks_out:
        print('No tracks processed — aborting.', file=sys.stderr)
        sys.exit(1)

    header = ('// Auto-generated by generate_peaks.py — do not edit manually.\n'
              '// Re-run: python3 generate_peaks.py\n')

    peaks_path = 'waveform_peaks.js'
    with open(peaks_path, 'w') as f:
        f.write(header + 'window.WAVEFORM_PEAKS = '
                + json.dumps(peaks_out, separators=(',', ':')) + ';\n')
    print(f'\nWrote {peaks_path} ({os.path.getsize(peaks_path)/1024:.1f} KB)')

    if beats_out:
        align_path = 'alignment_data.js'
        with open(align_path, 'w') as f:
            f.write(header + 'window.BEAT_DATA = '
                    + json.dumps(beats_out, separators=(',', ':')) + ';\n')
        print(f'Wrote {align_path} ({os.path.getsize(align_path)/1024:.1f} KB)')


if __name__ == '__main__':
    main()
